### ISSUE TITLE
Port is already being used using mdillon/postgis:latest

### ISSUE THREAD

**Issue by jesperlandmer** [appropriate/docker-postgis#102]
Getting this error message when running the image setup:

`listening on IPv4 address "127.0.0.1", port 5432`
`could not bind IPv6 address "::1": Cannot assign requested address`
`Is another postmaster already running on port 5432? If not, wait a few seconds and retry.`

I've already checked that nothing is running on port 5432 locally. I'm using docker-compose with a bridged network, so the port conflict shouldn't have anything to do with locally running ports anyways.

The weird thing is that it did work just a week ago, but now the port is occupied on that network.
I've even tried reinstalling docker, and it still isn't working. It is however working when I use the 9.6 version.

Changing the port doesn't do anything either.

My guess is that there are conflicting processes in the container

**Comment by ImreSamu** [comment]
Please check with the the official postgres image ( https://hub.docker.com/_/postgres/ )
Can you replicate the problems?

**Comment by ImreSamu** [comment]
> The weird thing is that it did work just a week ago, 

`mdillon/postgis:latest`  == `mdillon/postgis:10` (  Created:  6 weeks ago )

```
$ docker images
REPOSITORY                          TAG                        IMAGE ID            CREATED             SIZE 
mdillon/postgis                     10                         a6ca3144c3c6        6 weeks ago         630MB
mdillon/postgis                     latest                     a6ca3144c3c6        6 weeks ago         630MB
```

This is based on  `postgres:10`
https://github.com/appropriate/docker-postgis/blob/master/10-2.4/Dockerfile

So please test with `postgres:10` image.  Can you replicate ?

**Comment by jesperlandmer** [comment]
I've tried with both tags, and they don't seem to work. 
Dockerfile:
```
FROM mdillon/postgis

RUN apt-get update
RUN apt-get install -y  postgresql-plpython-$PG_MAJOR

# Install awscli, the credentials are set in the .env file
RUN apt-get install -y  python-pip
RUN pip install awscli

# ... some other work here copying sql files to container

```

docker-compose-file:
```
version: '3'
services:

    # Database (postgis)
    postgis:
        container_name: postgis
        build:
            context: ./postgis/
        restart: unless-stopped
        networks:
            - test-network
        ports:
            - "5001:5432"
        env_file: ./.env
        environment:
          # These are set empty to override the .env file. We need other
          # variables from there but these two interfere with the postgres
          # docker image setup.
          - PGDATABASE=
          - PGHOST=
        volumes:
          - test_data:/var/lib/postgresql
 
networks:
  test-network:

volumes:
  test_data:

```

Worked a week ago, but then when I removed the container, images and all volumes, this error message is shown:

```
postgis      | 2018-08-14 21:20:30.071 UTC [1] LOG:  listening on IPv4 address "127.0.0.1", port 5432
postgis      | 2018-08-14 21:20:30.071 UTC [1] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
postgis      | 2018-08-14 21:20:30.071 UTC [1] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
postgis      | 2018-08-14 21:20:30.074 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgis      | 2018-08-14 21:20:30.087 UTC [148] LOG:  database system was shut down at 2018-08-14 21:20:29 UTC
postgis      | 2018-08-14 21:20:30.094 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by jesperlandmer** [comment]
Okay, so when I switch network to network_mode host, it works. Although when I use another network, let's say `dev-network`, I still get the issue

**Comment by jesperlandmer** [comment]
Don't know if it has something to do with postgresql-plpython-10. When I run the Dockerfile without including the extension, I get this:

```
postgis      | 2018-08-15 07:35:17.591 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgis      | 2018-08-15 07:35:17.591 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgis      | 2018-08-15 07:35:17.594 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgis      | 2018-08-15 07:35:17.608 UTC [94] LOG:  database system was shut down at 2018-08-15 07:35:17 UTC
postgis      | 2018-08-15 07:35:17.659 UTC [1] LOG:  database system is ready to accept connections
```

But as soon as I include installing postgresql-plpython-10, I get this:

```
postgis      | 2018-08-15 07:37:04.252 UTC [1] LOG:  listening on IPv4 address "127.0.0.1", port 5432
postgis      | 2018-08-15 07:37:04.252 UTC [1] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
postgis      | 2018-08-15 07:37:04.252 UTC [1] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
postgis      | 2018-08-15 07:37:04.257 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgis      | 2018-08-15 07:37:04.272 UTC [94] LOG:  database system was shut down at 2018-08-15 07:37:04 UTC
postgis      | 2018-08-15 07:37:04.330 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by ImreSamu** [comment]
@jesperlandmer: 

probably a weird docker network problems.    :cry:     Try to search the docker / docker-compose problems ..

I have had a similar problem - and this tip was life-saving for me:
*  https://github.com/moby/moby/issues/20486#issuecomment-243688178

```
# be carefull! 
docker stop $(docker ps -aq)
docker rm   $(docker ps -aq)
#  docker system prune
systemctl stop docker
ls -la /var/lib/docker/network/files/local-kv.db
rm /var/lib/docker/network/files/local-kv.db
systemctl start docker
ls -la /var/lib/docker/network/files/local-kv.db
```

and upgrade your docker system if you need ..

```
$ docker -v
Docker version 18.06.0-ce, build 0ffa825
$ docker-compose -v
docker-compose version 1.22.0, build f46880fe
```

**Comment by jesperlandmer** [comment]
Okay, so I found this response to a similar issue [#230](https://github.com/docker-library/postgres/issues/230#issuecomment-268058832) for postgres. Apparently the postgres-package gets updated when you go to install plpython

**Comment by jesperlandmer** [comment]
Also, when I try the solutions mentioned there, I get this error:

`postgresql-plpython-10 : Depends: postgresql-10 (= 10.5-1.pgdg90+1) but 10.4-2.pgdg90+1 is to be installed`

Is there a possiblity to publish this image with a 10.4-2 version?

**Comment by jesperlandmer** [comment]
Worked when I specified postgres version 10.5. I’ll create a pull request!
