### ISSUE TITLE
Windows Docker Error

### ISSUE THREAD

**Issue by dopt** [appropriate/docker-postgis#103]
Hi , I was trying to run the DB docker on my windows environment, however I received the following error, when I execute the code following tutorial, any quick solution for this? Thanks.

First container creation is succeeded.
`$ docker run --name some-postgis -e POSTGRES_PASSWORD=mysecretpassword -d mdillon/postgis`

```
$ docker run --link some-postgis:postgres --rm postgres     sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'
Password for user postgres:
psql: fe_sendauth: no password supplied
```

**Comment by henrykironde** [comment]
Any reason why this was closed?
