### ISSUE TITLE
update-postgis.sh improvements

### ISSUE THREAD

**Issue by tisdall** [appropriate/docker-postgis#104]
I got the error `could not access file "$libdir/postgis-2.2": No such file or directory` mentioned in the readme and then ran `docker exec db update-postgis.sh` as suggested.  Unfortunately it didn't fix the issue.

I looked more into the script and it's because I have more databases then the default created ones.  Is it possible to change the script so additional database names could be passed in?

**Comment by md5** [comment]
That was done in #73, but it looks like the docs weren't updated. You should be able to just pass the additional database names as arguments to the script. Let me know if that's not the case and I we can reopen this issue.

**Comment by tisdall** [comment]
ugh..  sorry.  I think I was looking at an older commit instead of the current file in the repo.

Yeah, adding a note in the readme about passing database names would be good.  I ended up just manually running the needed commands.
