### ISSUE TITLE
Docker Postgis 2.5

### ISSUE THREAD

**Issue by Alados** [appropriate/docker-postgis#106]
When you can create new docker file for new postgis version? Or how I can do it?

**Comment by tourdownunder** [comment]
I have done this on my fork though only for postgres 11 in the 11b4-2.5 directory. I pasted it below. 

I had to remove the POSTGIS_VERSION environment variable and just used the scripts direct from the new packages [postgres postgis apt repo](http://ftp.postgresql.org/pub/repos/apt/pool/main/p/postgis/)

`
FROM postgres:11
MAINTAINER Mike Dillon <mike@appropriate.io>

ENV POSTGIS_MAJOR 2.5

RUN apt-get update \
      && apt-cache showpkg postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
      && apt-get install -y --no-install-recommends \
           postgresql-11-postgis-2.5 \
           postgresql-11-postgis-2.5-scripts \
           postgis-2.5 \
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/postgis.sh
COPY ./update-postgis.sh /usr/local/bin
`

**Comment by md5** [comment]
Hi @Alados. I appreciate your interest in learning how to update the image (and @tourdownunder for your feedback).

Updating Docker images always differ by author and often by image. In this case, it also differs based on whether we're talking about minor or patch version upgrades. We also have to take the Postgres EOL lifecycle into account.

In the case of #109, I did the following:

1. Saw there were some error reports and proposed fixes that I didn't fully read. For this image, that usually means a new version has been released.
2. `git checkout -b update-postgis`
2. `make update`
> Nothing happened, so I looked closer and the reports and fixes and noted we had had a PostGIS update from 2.4 to 2.5
4. `git branch -m postgis-2.5`
4. `for d in *-2.4; do mv $d ${d/2.4/2.5}; done`
4. `make update`
> Postgres 10 updated, but I got an error about 9.3. Looks like PostGIS 2.5 is not available for 9.3. Assuming it is EOL.
7. `rm -fr 9.3-2.5`
6. `make update`
7. `make build`
8. `git commit -av`, added a message
9. `git push -u origin postgis-2.5`
10. Opened #109
> Wondered if PostGIS 2.5 is packaged for Postgres 11... Someone might have mentioned this in an issue I didn't read yet...
11. `cp -r 10-2.5 11-2.5`
12. `make update`
13. `git add -A`
14. `git diff --staged`
> Noticed the staged diff had some trailing whitespace in the alpine variant...
15. `git reset HEAD`
16. Fixed trailing whitespace in `Dockerfile.alpine.template`
17. `make update`
18. `git commit -v Dockerfile.alpine.template !(11-2.5)/alpine/Dockerfile`
19. `git add -A`
20. `git diff --staged`
21. `make build`
22. `git commit -av`
23. `git push -u origin postgis-2.5`
24. Amend title of #109 to refer to both PostGIS 2.5 and Postgres 11

In your case, you would have had to do some extra stuff with your `git remote`s probably.

**Comment by md5** [comment]
Lol, the Postgres 11 comment is in this issue... At least I tried to be thorough
