### ISSUE TITLE
Auto-Run update-postgis.sh

### ISSUE THREAD

**Issue by msander** [appropriate/docker-postgis#110]
Auto-Updating the container can leave applications in an error state until you manually execute update-postgis.sh . Can we make this script be executed each time the container is started? Any drawbacks?

**Comment by md5** [comment]
The suggestion that @emartinez-usgs gives should work. You could probably even symlink `update-postgis.sh` into `/docker-entrypoint-initdb.d` directly.

That being said, the drawbacks are whatever the normal caveats are with upgrading PostGIS by running `ALTER EXTENSION`. I don't have a ton of experience with them, but I could see it being problematic to upgrade more than one minor release at a time or to upgrade blindly between major releases.

I don't think it makes sense to run `update-postgis.sh` by default.

**Comment by msander** [comment]
@md5 Would it be possible to add postgis version tags to the docker builds? When I point the container to e.g. mdillon/postgis:9.4 and pull the container regularly, the application might be broken before I execute this manually.
