### ISSUE TITLE
postgis version not available anymore

### ISSUE THREAD

**Issue by knowname** [appropriate/docker-postgis#111]
The postgis Version of the [Dockerfile 10-2.5](https://github.com/appropriate/docker-postgis/blob/master/10-2.5/Dockerfile) changed to `2.5.0+dfsg-2.pgdg90+1` instead of `2.5.0+dfsg-1.pgdg90+1`. I could not get the old version of it.

```
E: Version '2.5.0' for 'postgresql-10-postgis-2.5' was not found
E: Version '2.5.0' for 'postgresql-10-postgis-2.5-scripts' was not found
E: Version '2.5.0' for 'postgis' was not found
```

**Comment by knowname** [comment]
I fixed it by setting `ENV POSTGIS_VERSION 2.5.0+*`. Maybe not the best way, but this way the rebuild is possible.

**Comment by emilepetrone** [comment]
I just updated my version to `2.5.0+dfsg-2.pgdg90+1`

I would submit a PR, but I'm not confident this is the right fix. Either way, thank you for posting this issue.

**Comment by ImreSamu** [comment]
@emilepetrone ; @knowname ;

As I  know - the fixing is easy:
* `make update`   ( regenerate the Dockerfiles )
* `make build`      ( test build )

I have created a pull request #112
