### ISSUE TITLE
Upgrade to PostGIS 2.5 made container incompatible with data volume

### ISSUE THREAD

**Issue by vgeorge** [appropriate/docker-postgis#117]
I was using a container using `mdillon/postgis:9.6` when it had PostGIS 2.4. Recently I had to clean up disk space so deleted all docker images I had. When I tried to reinstantiate the container, it started giving the following error:

    could not access file "$libdir/postgis-2.4": No such file or directory

I suppose this is happening because a new version of PostGIS (2.5) was pushed to the same tag. Now I'm trying to figure out a way to recover the data, probably using the Dockerfile that had 2.4 version.

I suggest to rollback the tag `mdillon/postgis:9.6` to version 2.4 to avoid others face the same issue as me, and also pushing 2.5 into a specific tag, like `mdillon/postgis:9.6-2.5`.

**Comment by vgeorge** [comment]
Ok, thanks.

**Comment by md5** [comment]
I would only add that if you're using this image in production or some other setting where you want reproducibility, you might want to consider retagging this image in your own namespace with your own tags as part of your provisioning/deployment process. This image was never intended to be a turn-key solution for anyone.

**Comment by vgeorge** [comment]
I understand, I'm not using it in production. Thanks very much for your help!
