### ISSUE TITLE
postgis.sh: 9  Bad substitution

### ISSUE THREAD

**Issue by loic-lopez** [appropriate/docker-postgis#119]
Hello, when the database system start for the first time it displays:
```
waiting for server to start....2018-12-11 14:59:23.401 UTC [42] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2018-12-11 14:59:23.528 UTC [43] LOG:  database system was shut down at 2018-12-11 14:59:23 UTC
2018-12-11 14:59:23.575 UTC [42] LOG:  database system is ready to accept connections
 done
server started
/docker-entrypoint-initdb.d/postgis.sh: 9: /docker-entrypoint-initdb.d/postgis.sh: Bad substitution
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh

```

So when i tried to create a table with a position datatype:
```
 SQLSTATE[42704]: Undefined object: 7 ERROR:  type "geography" does not exist at character 91 (SQL: create table "check_points" ("id" uuid not null, "type" varchar(255) not null, "location" GEOGRAPHY(POLYGON, 4326) not null, "run_id" uuid not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null))
```

**Comment by bukowa** [comment]
````bash
    build:
      ./docker-postgis-master/11-2.5
````

````bash
postgis_1  |  done
postgis_1  | server started
postgis_1  | CREATE DATABASE
postgis_1  |
postgis_1  |
postgis_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh
postgis_1  | /docker-entrypoint-initdb.d/postgis.sh: 9: /docker-entrypoint-initdb.d/postgis.sh: Bad substitution
````

Same error on my side.

**Comment by loukash** [comment]
Fix:
```bash
chmod -x initdb-postgis.sh
chmod -x update-postgis.sh
```

https://github.com/docker-library/postgres/blob/master/9.6/docker-entrypoint.sh#L132-L144

**Comment by md5** [comment]
It looks like the repository got checked out somewhere that didn't preserve Unix permissions, so the executable bit was lost. It's there in the Git repository.

**Comment by md5** [comment]
Sorry, I got it backwards.

The `initdb-postgis.sh` script is intentionally not set with the execute bit so that it will be sourced by the `postgres` entrypoint instead of executed. This is what makes the `$psql` variable available for use.

I think you may be running into this if you're on Windows and bind mounting in the source: https://github.com/docker-library/postgres/pull/452#issuecomment-393259603

**Comment by realmhamdy** [comment]
I'm getting this same error too. I'm building on Windows. IDK what to do. Is there a fix that's not Windows-specific somehow?

**Comment by bukowa** [comment]
Take a look at line ending (different for Unix different for Windows). I had some problems with that.

**Comment by TOTOleHero** [comment]
Hello,

If you change the shel, it work

change `#!/bin/sh` by `#!/bin/bash` in file `initdb-postgis.sh`

**Comment by TOTOleHero** [comment]
Hello, 

Change the shell and ths srcipt work :

Change `#!/bin/sh` by  `#!/bin/sh` in file `initdb-postgis.sh`

But after, i have another error
