### ISSUE TITLE
Alpine image for 11/2.5 does not build (FIX IN COMMENT)

### ISSUE THREAD

**Issue by geotom** [appropriate/docker-postgis#120]
I'm using your dockerfile for alpine linux to build a postgis image. Thx for your work. I was actually copying the first part of your image recipe (https://github.com/appropriate/docker-postgis/blob/master/11-2.5/alpine/Dockerfile) and added my additional stuff.

It worked (=built) flawlessly 3 weeks ago and suddenly the image can't be build any longer. The error happens in line 45

> && ./configure \

 The configure script stops with 

> checking for library containing GDALAllRegister... no
> configure: error: could not find GDAL

Do you have any idea what the problem could be or have you tested it yourself already?

**Comment by wandth** [comment]
My further look into this led me to the following unsatisfied dpendeny of gdal:

`ldd /usr/lib/libgdal.so`

outputs...

> Error loading shared library libsqlite3.so.0: No such file or directory (needed by /usr/lib/libgdal.so)
> 	libgif.so.7 => /usr/lib/libgif.so.7 (0x7fe17121c000)
> 	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x7fe1724bd000)
> 	libtiff.so.5 => /usr/lib/libtiff.so.5 (0x7fe172453000)
> 	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x7fe170fee000)
> 	libpq.so.5 => /usr/local/lib/libpq.so.5 (0x7fe170da8000)
> 	libcurl.so.4 => /usr/lib/libcurl.so.4 (0x7fe1723e0000)
> 	libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0x7fe170b2b000)
> 	libz.so.1 => /lib/libz.so.1 (0x7fe170914000)
> 	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fe1705c1000)
> 	libc.musl-x86_64.so.1 => ldd (0x7fe172292000)
> 	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fe1703af000)
> 	libssl.so.1.0.0 => /lib/libssl.so.1.0.0 (0x7fe170146000)
> 	libcrypto.so.1.0.0 => /lib/libcrypto.so.1.0.0 (0x7fe16fd27000)
> 	libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x7fe1723bc000)
> 	libssh2.so.1 => /usr/lib/libssh2.so.1 (0x7fe172392000)
> 	libssl.so.1.1 => /lib/libssl.so.1.1 (0x7fe16fca7000)
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_int: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_blob: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_int: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_int64: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_create_module_v2: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_double: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_user_data: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_blob: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_type: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_malloc: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_reset: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_null: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_double: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_int64: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_text: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_close: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_create_function: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_vfs_register: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_last_insert_rowid: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_name: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_mprintf: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_double: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_double: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_text: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_text: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_origin_name: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_blob: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_prepare_v2: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_errmsg: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_int64: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_changes: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_int: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_text: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_bytes: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_type: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_free_table: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_open_v2: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_free: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_exec: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_step: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_int64: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_declare_vtab: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_vfs_unregister: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_finalize: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_null: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_vfs_find: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_auto_extension: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_blob: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_open: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_bytes: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_count: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_decltype: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_table_name: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_clear_bindings: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_get_table: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_int: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_blob: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_double: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_int: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_int64: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_null: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_bind_text: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_changes: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_close: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_blob: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_bytes: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_count: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_decltype: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_double: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_int: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_int64: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_name: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_table_name: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_text: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_column_type: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_create_function: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_create_module: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_declare_vtab: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_errcode: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_errmsg: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_exec: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_finalize: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_free: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_free_table: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_get_table: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_last_insert_rowid: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_libversion_number: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_malloc: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_mprintf: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_open: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_prepare: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_realloc: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_reset: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_blob: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_double: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_error: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_int: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_int64: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_null: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_text: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_result_value: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_snprintf: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_step: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_total_changes: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_user_data: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_blob: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_bytes: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_double: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_int: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_int64: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_numeric_type: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_text: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_value_type: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_vmprintf: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_prepare_v2: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_create_module_v2: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_open_v2: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_vfs_find: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_vfs_register: symbol not found
> Error relocating /usr/lib/libgdal.so: sqlite3_vfs_unregister: symbol not found

**Comment by wandth** [comment]
The fix is to install the alpine linux package **sqlite-libs**

**Comment by ImreSamu** [comment]
@wandth :  please verify my proposal ( #121 )

**Comment by wandth** [comment]
Yes, just tried manually to change the order of the repositories (testing before main) andit works no without the additional installation of the sqlite-libs.

**Comment by md5** [comment]
Closed in https://github.com/appropriate/docker-postgis/pull/121
