### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by JerryGreen** [appropriate/docker-postgis#123]
There's a problem with this container's versioning

For example, I have `9.6` tag, which I describe in docker-compose:
```
  postgres:
    image: mdillon/postgis:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
```

I regularly (but not very much) do `docker-compose pull && docker-compose down && docker-compose up -d`, and my `9.6.` gets updated every few months - and I get various errors

I don't remember my first problem with this container (happened maybe a year ago, I haven't created an issue), but [there's the second one](https://github.com/appropriate/docker-postgis/issues/122)

I can't be sure that my app won't be broken at some moment ☹️This is not a good practice

Just compare [mdillon/postgis tag list](https://hub.docker.com/r/mdillon/postgis/tags) and [postgres tag list](https://hub.docker.com/_/postgres/?tab=tags)

Can you follow the versioning more strictly, and make tags for minor versions like `9.6.9`, `9,6.10`, `9.6.11`, etc? (well, at least, for new versions)

**Comment by JerryGreen** [comment]
@md5 no any comments, just a closing?

(cool nickname btw 😀)

**Comment by md5** [comment]
Sorry, but this has been discussed ad nauseum. I don't have the resources either in terms of infrastructure or my time or interest to have a more robust tagging scheme. It's a combination of how PGDG manages their repos (they delete old versions) and the limitations of the Docker Cloud build infrastructure (though that seems to have improved)
