### ISSUE TITLE
Cannot load csv file (could not open file "c:\Users\egarfel\Desktop\test.csv" for reading: No such file or directory)

### ISSUE THREAD

**Issue by lipiss** [appropriate/docker-postgis#125]
When trying to load a csv file to a table with the following command:
postgres=# \COPY sector_location_csv  FROM 'c:\Users\egarfel\Desktop\test.csv' DELIMITER ',' CSV
or from dbvisualizer like:
COPY
sector_location_csv 
FROM
'c:\Users\egarfel\Desktop\test.csv' 
WITH (FORMAT csv, DELIMITER ',',  NULL 'NULL', HEADER);

I get 
ERROR: could not open file "c:\Users\egarfel\Desktop\test.csv" for reading: No such file or directory
Hint: COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

Has anyone gone through this issue!? I have been trying different things like permissions etc... But cant think of what else can I try.

Thank you very much.

**Comment by lipiss** [comment]
It could be some windows docker configuration... not sure.

**Comment by md5** [comment]
Since the error is "No such file or directory", I think this is a Windows drive mapping thing. Once you get that sorted, I wouldn't be surprised if you run into other issues. I've always had lots of permission-related and other issues with `COPY FROM`.

**Comment by md5** [comment]
You might have some luck on the [Docker Community Forums](https://forums.docker.com/) with Windows-related questions 👍
