### ISSUE TITLE
Official documentation says to not install on postgres user/ database which is the default. 

### ISSUE THREAD

**Issue by arianitu** [appropriate/docker-postgis#127]
Hello, the init script installs Postgis on the postgres database which is the default database and user on a classic Postgres installation.

The documentation here says to NOT do that: https://postgis.net/install/

I am unsure of why in big capitals it says to not do that, but I'm now adjusting the Postgis script to remove anything that creates an extension and I'm creating them manually in the database.

**Comment by md5** [comment]
The init script installs into `$POSTGRES_DB`, which the `postgres` image defaults to `$POSTGRES_USER`. This does indeed default to `postgres`, so with all defaults it will install PostGIS into that database. In the absence of any documented adverse affects with running that configuration (other than it just not being a good idea), I don't think there's anything to be done in this image.
