### ISSUE TITLE
PostgreSQL 12 image

### ISSUE THREAD

**Issue by axelfontaine** [appropriate/docker-postgis#135]
Now that PostgreSQL 12 Beta 1 has been released and the official Docker Postgres 12-beta1 image is available: https://hub.docker.com/_/postgres?tab=description

**Comment by tdamsma** [comment]
See #134

**Comment by NicolasCaous** [comment]
Any updates on this?

**Comment by md5** [comment]
See #143. I'm not adding new versions to this image
