### ISSUE TITLE
Changing locale?

### ISSUE THREAD

**Issue by lucamanga** [appropriate/docker-postgis#136]
Hello,
I run the Docker instance with these parameters:
```
  docker run \
    -v /opt/pgdata:/var/lib/postgresql/data \
    -e LANG=it_IT.UTF-8 \
    -e LC_ALL=it_IT.UTF-8 \
    -e POSTGRES_PASSWORD=PWD \
    --network=qgis-net \
    --name=postgis \
    -d mdillon/postgis:11
```
the problem is that running this container give me these errors:
```
bash: warning: setlocale: LC_ALL: cannot change locale (it_IT.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (it_IT.UTF-8)
2019-06-12 13:48:00.918 UTC [1] LOG:  invalid value for parameter "lc_messages": "it_IT.utf8"
2019-06-12 13:48:00.918 UTC [1] LOG:  invalid value for parameter "lc_monetary": "it_IT.utf8"
2019-06-12 13:48:00.918 UTC [1] LOG:  invalid value for parameter "lc_numeric": "it_IT.utf8"
2019-06-12 13:48:00.918 UTC [1] LOG:  invalid value for parameter "lc_time": "it_IT.utf8"
```
how can I fix this?

**Comment by ImreSamu** [comment]
> Changing locale?

Hi,

As written in the readme - _"This image is based on the official [postgres](https://registry.hub.docker.com/_/postgres/)  image "_ so  probably the official - "Locale Customization" tips -  should be work with this image.
see: https://hub.docker.com/_/postgres/

based on the example - probably the following ( not tested ) example should work

```dockerfile
FROM mdillon/postgis:11
RUN localedef -i it_IT -c -f UTF-8 -A /usr/share/locale/locale.alias it_IT.UTF-8
ENV LANG it_IT.utf8
```
see more: https://github.com/docker-library/postgres/issues/510#issuecomment-451290525

**Comment by lucamanga** [comment]
Great!

I think this could be in your readme.md, too
