### ISSUE TITLE
Version '2.4.3+dfsg-2.pgdg90+1' for 'postgresql-10-postgis-2.4' was not found

### ISSUE THREAD

**Issue by mhyousefi** [appropriate/docker-postgis#162]
I'm using [this build](https://github.com/appropriate/docker-postgis/blob/f6d28e4a1871b1f72e1c893ff103f10b6d7cb6e1/10-2.4/Dockerfile) with the following envs:
```
ENV POSTGIS_MAJOR 2.4
ENV POSTGIS_VERSION 2.4.3+dfsg-2.pgdg90+1
```

And I am getting the following error:
```
E: Version '2.4.3+dfsg-2.pgdg90+1' for 'postgresql-10-postgis-2.4' was not found
E: Version '2.4.3+dfsg-2.pgdg90+1' for 'postgresql-10-postgis-2.4-scripts' was not found
E: Version '2.4.3+dfsg-2.pgdg90+1' for 'postgis' was not found
```

**Comment by mhyousefi** [comment]
Can you at least give some feedback??

**Comment by md5** [comment]
Please make an attempt to look at the existing issues and PRs before posting new issues. This project is effectively unmaintained

**Comment by mhyousefi** [comment]
Alright thanks. But, I appreciate if you could help out with this [question](https://stackoverflow.com/questions/59882544/error-unsatisfiable-constraints-when-installing-postgis-on-the-alpine-docker-im).
