### ISSUE TITLE
Specify postgis versions in docker tags

### ISSUE THREAD

**Issue by JacobHayes** [appropriate/docker-postgis#18]
We have deployed databases that are on `9.3`/`2.1` (in process of migrating to `9.5`/`2.2`) and don't want to upgrade developer databases until we have a clear migration path for deployed environments. Since these images aren't tagged with the postgis version we can't stay on `2.1` without vendoring the old dockerfile (which we'd rather not do).

`9.x`/`2.1` combinations wouldn't necessarily need to be maintained, like `9.0` is now - tagged, but not updated.

**Comment by JacobHayes** [comment]
I don't think this is a PR sort of thing since the tags are handled outside this repo, otherwise I'd submit one. :)

**Comment by md5** [comment]
Since I'm using Docker Hub's automated builds, it's difficult for me to maintain multiple sets of tags. The other complication is the fact that there is no longer a 2.1 version of the `postgis` package on `apt.postgresql.org`, so it's no longer possible to build a 9.3-2.1 image unless you leave out that package (resulting in the userspace utilities being dropped).

I took a look at the build details on Docker Hub and it looks like you should be able to pull the last build of 9.3-2.1 like so:

```console
$ docker pull mdillon/postgis@sha256:aff8d882c76395e7c76bd1910b130c601d4ca2984c900c1723a167b770fb19d8
```

**Comment by md5** [comment]
See #8 and http://www.postgresql.org/message-id/flat/CAG077fAyaOdrpqg46ah_8N6MhUR-pLP3b85aePgKwbO70FKuRw@mail.gmail.com#CAG077fAyaOdrpqg46ah_8N6MhUR-pLP3b85aePgKwbO70FKuRw@mail.gmail.com for some more background.

**Comment by JacobHayes** [comment]
Unfortunate how the userland package is managed. Thanks for the image/sha, that'll work great!

I'm haven't used the automated builds, but could there be Dockerfiles, with just `FROM mdillon/postgis@sha256:{latest_built_sha}` where that would point to the pre-2.2 image tags? That's basically what I plan to do internally.

**Comment by md5** [comment]
There could be Dockerfiles like that, but I'd rather not maintain them myself. The problem is that if there are security updates for the `postgres` images, I won't be able to update the 2.1 images unless I have an alternate Dockerfile that removes the `postgis` package.

**Comment by JacobHayes** [comment]
I don't mean maintain them, simply to create them, have them tagged as `9.x-2.1` (maybe with a `-deprecated` or similar) and then they could be removed. There is currently a `9.0` image tag that won't be updated, these would be in the same boat.

Any way, thank you for your help, I'll go ahead and close this.
