### ISSUE TITLE
Error on pre-existing databases with new images if it was initialized with PostGIS 2.1

### ISSUE THREAD

**Issue by alvingonzales** [appropriate/docker-postgis#20]
When updating/rebuilding images with the latest versions (which has PostGIS 2.2 instead), queries fail with "OperationalError: could not access file "$libdir/postgis-2.1": No such file or directory" on pre-existing databases created before #8 was in place.

Per upgrading information from http://postgis.net/install/, you need to execute more commands for each database so you can complete the upgrade to 2.2:

```
-- Upgrade PostGIS (includes raster)
ALTER EXTENSION postgis 
 UPDATE TO "2.2.1";
-- Upgrade Topology
ALTER EXTENSION postgis_topology 
 UPDATE TO "2.2.1";

-- Upgrade US Tiger Geocoder
ALTER EXTENSION postgis_tiger_geocoder 
 UPDATE TO "2.2.1";
```

While this can be done manually by admins, wouldn't it perhaps be better if this was included in the startup if it detects the default database is not yet upgraded from 2.1 to 2.2?

If not, it would really be better to have a version pin for 2.1. Looking at #8 where 2.2 was introduced, this may seem hard, but since that issue is closed, I've made this new one so this can be tracked separately.

**Comment by md5** [comment]
@alvingonzales Were you able to follow those instructions successfully? If so, I think the best that can be done is to document what needs to be done when upgrading.

It may also make sense to go back to including the PostGIS version number in the tags on Docker Hub, but that was a bit of a pain to configure when I had it before. It isn't isn't straightforward to retroactively create "2.1" tags for existing builds with an automated build as far as I know.

**Comment by alvingonzales** [comment]
@md5 , Yes, following the additional upgrade instructions fixed the OperationalError, and made the database work again for PostGIS related queries.

I'm not very familiar with docker hub automated builds yet (since we host our images privately with our CI server), But I guess yes, it might be best to update README.md to add a note regarding the upgrade for now.

**Comment by AdrianRibao** [comment]
Same issue but this time for postgis 2.3

We need to run:

```
-- Upgrade PostGIS (includes raster)
ALTER EXTENSION postgis 
 UPDATE TO "2.3.0";

-- Upgrade Topology
ALTER EXTENSION postgis_topology 
 UPDATE TO "2.3.0";
 
-- Upgrade US Tiger Geocoder
ALTER EXTENSION postgis_tiger_geocoder 
 UPDATE TO "2.3.0";
```

**Comment by md5** [comment]
@AdrianRibao Were you able to make this approach work? If so, how were you able to run the command?

I'd be happy to document a recommended procedure for dealing with updates or even providing a script of some sort the help streamline that procedure (assuming it's either opt-in or has strong guarantees about not corrupting the user's database).

Does anyone know how this is handled when updating the `postgis` packages in a non-container scenario?

**Comment by md5** [comment]
Answering my own question perhaps, it looks like the failure actually happens at query time, so it should be pretty straightforward to include a script that can be run with `docker exec` that can detect the version difference and run the update command.

**Comment by AdrianRibao** [comment]
@md5 yes, it works running that commands on the databases that use postgis.

**Comment by lechup** [comment]
I had the same issue today - upgrading 2.2 to 2.3.

Running commands fixed problems for me.

Thanks @AdrianRibao and @alvingonzales for sharing!

**Comment by lechup** [comment]
I've created #54 to provide a way to handle that case...
