### ISSUE TITLE
PostGIS 2.2.2 released

### ISSUE THREAD

**Issue by ximex** [appropriate/docker-postgis#22]
http://postgis.net/2016/03/22/postgis-2.2.2/

**Comment by md5** [comment]
Thanks! I saw the announcement, but Apt packages were not yet available
when I checked.

**Comment by md5** [comment]
They appear to have been uploaded yesterday to the `jessie-pgdg-testing` repo, but they're not yet available in `jessie-pgdg`.

**Comment by md5** [comment]
@ximex The updated 2.2.2 images are available on Docker Hub :+1:
