### ISSUE TITLE
Issue with postgis package on 9.4 & 9.5

### ISSUE THREAD

**Issue by josephbisaillon** [appropriate/docker-postgis#23]
I keep having issues when running the dockerFile here

https://github.com/appropriate/docker-postgis/blob/master/9.4-2.2/Dockerfile

It wasn't giving me issues earlier in the week, but I recently destroyed my images and tried to create a new one with the same dockerfile and keep getting the same errors. Tried doing it on multiple containers, including using postgres:9.5, is this a debian apt-get issue? I'm not sure. 

Also have tried on multiple computers. same result, windows or mac.

```E: Version '2.2.1+dfsg-2.pgdg80+1' for 'postgresql-9.4-postgis-2.2' was not found
E: Version '2.2.1+dfsg-2.pgdg80+1' for 'postgis' was not found
The command '/bin/sh -c apt-get update       && apt-get install -y --no-install-recommends            postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION            postgis=$POSTGIS_VERSION       && rm -rf /var/lib/apt/lists/*       && apt-get -y autoclean' returned a non-zero code: 100```

**Comment by josephbisaillon** [comment]
temp fix I was able to use was 

ENV POSTGIS_MAJOR 2.2
ENV POSTGIS_VERSION 2.1.4+dfsg-3

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
           postgis=$POSTGIS_VERSION \
      && rm -rf /var/lib/apt/lists/*

**Comment by md5** [comment]
@josephbisaillon The issue is that the 2.2.1 package was removed from `apt.postgresql.org` and replaced with 2.2.2. I've opened #24 to update to 2.2.2. I'll merge it later today, assuming the tests pass.

**Comment by md5** [comment]
@josephbisaillon The 9.4 and 9.5 images completed successfully on Docker Hub :+1:

**Comment by josephbisaillon** [comment]
@md5 thanks for the fast turnaround! :+1: :dancers:

**Comment by md5** [comment]
@josephbisaillon No problem. It's an easy update and I've been expecting it for a week or more.
