### ISSUE TITLE
Enabling hstore extension for postgis db

### ISSUE THREAD

**Issue by dooman87** [appropriate/docker-postgis#25]
I was trying to use osm2pgsql command to import data to a db. However got the error:

`type "hstore" does not exist`

Error was fixed by enabling hstore extension for the db. Do you think it might be handy to enable it by default during db creation phase? 

I could prepare PR if the answer will be "yes".

**Comment by md5** [comment]
@dooman87 I don't have a strong sense of how common the need for `hstore` in conjunction with PostGIS is, so I'm happy to defer judgement on that point.

Feel free to create a PR, although I may not get to it for a few days.

Alternatively, you could add an additional script to `/docker-entrypoint-initdb.d/` to install `hstore` yourself in a derived image.

**Comment by dooman87** [comment]
@md5 Alright, looks like osm2pgsql is using hstore to import osm tags. Just found explanation there http://gis.stackexchange.com/questions/6379/what-are-the-pros-and-cons-of-hstore-data-type-in-postgis

I'll use your image as base for mine then. Thanks for a quick response and great job, appreciate that!
