### ISSUE TITLE
Having issue when putting in env vars

### ISSUE THREAD

**Issue by pythdasch** [appropriate/docker-postgis#28]
Hi,

I already installed postgis without problem on another dokku machine. But since I upgraded on another machine I've somme issue to install the postgis.

I've done the instructions, and when I try to use the images for postgres plugins he says : 
docker: Error parsing reference: "mdillon/postgis\" latest" is not a valid repository/tag.

here are my env 

export POSTGRES_IMAGE="mdillon/postgis"
export POSTGRES_IMAGE_VERSION="latest"

thanks in advance

**Comment by md5** [comment]
@pythdasch I'm not totally sure how you're using those environment variables, but the issue appears to be that you're asking Docker to run `"mdillon/postgis\" latest"` instead of `"mdillon/postgis:latest"`

**Comment by pythdasch** [comment]
ok, I'll try :) thx @md5

**Comment by md5** [comment]
@pythdasch I'm going to close this issue. Please comment if you need me to reopen it.
