### ISSUE TITLE
9.5-2.2 build error

### ISSUE THREAD

**Issue by im4LF** [appropriate/docker-postgis#33]
With specifying POSTGIS_VERSION 2.2.2+dfsg-1.pgdg80+1 docker not build:

```
E: Version '2.2.2+dfsg-1.pgdg80+1' for 'postgresql-9.5-postgis-2.2' was not found
E: Version '2.2.2+dfsg-1.pgdg80+1' for 'postgis' was not found
```

Need change POSTGIS_VERISON to 2.2.2+dfsg-1.pgdg80+4

May be there is no need to specifying POSTGIS_VERSION ?

**Comment by md5** [comment]
I fixed this in #32

**Comment by md5** [comment]
Unfortunately, the automated build on Docker Hub is not working since I moved the repository. I've manually kicked off the builds.

**Comment by md5** [comment]
My apologies! I just realized I hadn't merged that PR yet...
