### ISSUE TITLE
Startup time in Continuous Build scenarios

### ISSUE THREAD

**Issue by mmmmmrob** [appropriate/docker-postgis#34]
Hi,

I'm planning to swap over from the official postgres image to mdillon/postgis to start working with postgis features in a site I'm building. We use docker in circleci for continuous build and test, and then docker cloud for continuous deployment. This works well with postgres but not with postgis.

We have (in essence) three containers: web, test and db. Web has a link to db; test has a link to web.

The postgres docker container starts postgres almost immediately and is ready to receive connections. The postgis image takes a lot longer to ready the postgis extension and start accepting connections. This kind of problem is not uncommon in docker when services take some time to come online.

docker recently introduced HEALTHCHECK to allow a container to say when it was ready to receive requests, and to continue to provide a status once running. (https://docs.docker.com/engine/reference/builder/#/healthcheck)

It would be super helpful if mdillon/postgis implemented HEALTHCHECK.

**Comment by md5** [comment]
It looks like `HEALTHCHECK` is a Docker 1.12 addition, so I don't think it's supported yet on Docker Hub's automated builds.

I also feel this addition would be better made in the `postgres` image itself. The reasons I think that's the case are twofold. First, it seems like other derived images with long running init scripts could benefit from the same check (or even the base image in the case of disk I/O errors or heavy CPU load). Second, I think the check itself would be a generic “is Postgres accepting connections on a non-local port”, not anything PostGIS-specific.

Does that make sense or am I missing something?

**Comment by mmmmmrob** [comment]
makes perfect sense
