### ISSUE TITLE
Possible to link against GEOS 3.5.0+?

### ISSUE THREAD

**Issue by ezheidtmann** [appropriate/docker-postgis#39]
Hey there, 

I have a query that uses ST_ClipByRect, which requires postgis 2.2 and GEOS 3.5+. Any idea how I can produce such an image? 

Thanks,
Evan

P.S. Current pg95 image is producing this error for my query: `InternalError("The GEOS version this PostGIS binary was compiled against (34) doesn't support 'GEOSClipByRect' function (3.5.0+ required)\n",)`

**Comment by ezheidtmann** [comment]
I did it by inheriting from your image and building GEOS and Postgis from source. Works for my (dev) purposes.

https://github.com/knocksoftware/docker-postgis-geos35

https://hub.docker.com/r/ezheidtmann/docker-postgis-geos35/

`docker pull ezheidtmann/docker-postgis-geos35

**Comment by md5** [comment]
Glad you figured it out. Once updated packages become available, I can upgrade this image, but I'd like to keep it using prebuilt packages.
