### ISSUE TITLE
Please add postgresql 9.6 with postGIS 2.3

### ISSUE THREAD

**Issue by cg-d** [appropriate/docker-postgis#40]
Can you please add a branch for postgresql 9.6 with postGIS 2.3?

Cheers
CGD

**Comment by md5** [comment]
Looks like the debs are available in PGDG, so it should be possible to make such an image. I'm not sure when I'll have time, but a PR would be welcome.

**Comment by JacobHayes** [comment]
I'm willing to put together a PR. Would you like all images be updated to postgis 2.3 or just 9.6 for now?
