### ISSUE TITLE
Package Issues

### ISSUE THREAD

**Issue by ramalhoruben** [appropriate/docker-postgis#43]
Hello,

I had no problems installing via the automated build, but if I download the docker file and corresponding script and try to manually build the file the installation halts at step 5 with the following error message:

```
E: Version '2.3.0+dfsg-2~132.gitddacceb.pgdg80+6' for 'postgresql-9.6-postgis-2.3' was not found
E: Version '2.3.0+dfsg-2~132.gitddacceb.pgdg80+6' for 'postgis' was not found
The command '/bin/sh -c apt-get update       && apt-get install -y --no-install-recommends            postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION            postgis=$POSTGIS_VERSION       && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

```
I am using docker version 1.9.1 on a opensuse machine. This happened both with the version for pg 9.5 and 9.6

Thanks

**Comment by md5** [comment]
@ramalhoruben The Postgres `apt` repository (PGDG) has the unfortunate policy of deleting old packages when new ones are uploaded (it may only be the `postgis`-related image, but I think it's across the board if I recall). This means that this image frequently breaks.

I've pushed a branch that should fix this. See #44, which I'll merge once the CI builds complete.

**Comment by md5** [comment]
The Travis builds look like a bit of a mess, unfortunately. Some of them look like they failed due to download errors, but other look like the updated `postgis` package may actually be broken.

**Comment by ramalhoruben** [comment]
Oh, so  sorry to hear that. Thanks for the explanation.
I guess I will have to wait.

**Comment by md5** [comment]
@ramalhoruben Things should be in better shape with the latest builds of this image now that I've sorted out the issues with #44 and merged it.

**Comment by ramalhoruben** [comment]
The image was built successfully. And everything seems to be ok!

Thanks
