### ISSUE TITLE
alpine variants

### ISSUE THREAD

**Issue by dsbaars** [appropriate/docker-postgis#46]
The official `postgres` repository offers alpine variants, it would be really nice if you could provide alpine variants as well :)

**Comment by md5** [comment]
I'm happy to review a PR for this, but I don't have time to look into this myself.

Off the top of my head, my main concern would be about how PostGIS itself is built/installed for this image.

**Comment by dsbaars** [comment]
Did an attempt, but the official `docker-library` image didn't contain libpq, so that would mean you'd also need another postgres baseimage: https://gist.github.com/dsbaars/99e33a0d82255d129026beb6a49074b8

Then the following successfully builds:
```Dockerfile
FROM pg-alpine 
#modified from docker-library
MAINTAINER Djuri Baars <dsbaars@gmail.com>

ENV POSTGIS_MAJOR 2.3
ENV POSTGIS_VERSION 2.3.0

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk add --update --no-cache perl file geos@testing geos-dev@testing  \
                                libxml2-dev gdal@testing gdal-dev@testing \
                                proj4@testing proj4-dev@testing \
                                gcc make libgcc g++

RUN cd /tmp && \
    wget http://download.osgeo.org/postgis/source/postgis-${POSTGIS_VERSION}.tar.gz -O - | tar -xz && \
    chown root:root -R postgis-${POSTGIS_VERSION} && \
    cd /tmp/postgis-${POSTGIS_VERSION} && \
    ./configure  --with-geosconfig=/usr/bin/geos-config && \
    echo "PERL = /usr/bin/perl" >> extensions/postgis/Makefile && \
    echo "PERL = /usr/bin/perl" >> extensions/postgis_topology/Makefile && \
    make -s && \
    make -s install

RUN rm -rf /tmp/postgis-${POSTGIS_VERSION}

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/postgis.sh
```

**Comment by md5** [comment]
@dsbaars It may be worth opening a discussion with the `docker-library` maintainers about adding `libpq` to the `postgres:alpine` image if it doesn't greatly increase the size of the image. Is it right to assume that the Debian-based images include `libpq` or does that get pulled in as a dependency of `postgis` from PGDG? Either way, it probably doesn't have the `libpq` headers necessary to build PostGIS.

**Comment by boozedog** [comment]
Looks promising!!
