### ISSUE TITLE
Docker Build Failure

### ISSUE THREAD

**Issue by Brumstar** [appropriate/docker-postgis#47]
Hey, I'm trying to build this docker image on an Ubuntu 15.10 machine. When I run the command "`sudo docker build -t postgres_image .`", I get the build version errors found bolded below. Can anyone help with this?

Sending build context to Docker daemon 17.41 kB
Step 1 : FROM postgres:9.6
 ---> d12be754b938
Step 2 : MAINTAINER Mike Dillon <mike@appropriate.io>
 ---> Using cache
 ---> c36894d74f99
Step 3 : ENV POSTGIS_MAJOR 2.3
 ---> Using cache
 ---> fe4d2edd379a
Step 4 : ENV POSTGIS_VERSION 2.3.0+dfsg-2.pgdg80+1
 ---> Using cache
 ---> 3dd26124953f
Step 5 : RUN apt-get update       && apt-get install -y --no-install-recommends            postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION            postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION            postgis=$POSTGIS_VERSION       && rm -rf /var/lib/apt/lists/*
 ---> Running in 8e07192ff31d
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://apt.postgresql.org jessie-pgdg InRelease [46.5 kB]
Get:3 http://apt.postgresql.org jessie-pgdg/main amd64 Packages [107 kB]
Ign http://deb.debian.org jessie InRelease
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [421 kB]
Get:5 http://apt.postgresql.org jessie-pgdg/9.6 amd64 Packages [20 B]
Get:6 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:7 http://deb.debian.org jessie Release.gpg [2,373 B]
Get:8 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:9 http://deb.debian.org jessie Release [148 kB]
Get:10 http://deb.debian.org jessie/main amd64 Packages [9,064 kB]
Fetched 10.0 MB in 3s (2,929 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
**E: Version '2.3.0+dfsg-2.pgdg80+1' for 'postgresql-9.6-postgis-2.3' was not found
E: Version '2.3.0+dfsg-2.pgdg80+1' for 'postgresql-9.6-postgis-2.3-scripts' was not found
E: Version '2.3.0+dfsg-2.pgdg80+1' for 'postgis' was not found**
The command '/bin/sh -c apt-get update       && apt-get install -y --no-install-recommends            postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION            postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION            postgis=$POSTGIS_VERSION       && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by ImreSamu** [comment]
as I see it is changed to `2.3.1+dfsg-1.pgdg80+1`

### my method to query:
```bash
docker run -it --rm postgres:9.6 /bin/bash
apt-get update && apt-cache policy postgresql-9.6-postgis-2.3
```

### log
```bash
~/docker-postgis/9.6-2.3$ docker run -it --rm postgres:9.6 /bin/bash
root@6e812f2b4c93:/# apt-get update && apt-cache policy postgresql-9.6-postgis-2.3
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://apt.postgresql.org jessie-pgdg InRelease [46.5 kB]                                                                        
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [421 kB]          
Ign http://deb.debian.org jessie InRelease                                                                                             
Get:4 http://deb.debian.org jessie-updates InRelease [145 kB]              
Get:5 http://apt.postgresql.org jessie-pgdg/main amd64 Packages [107 kB]            
Get:6 http://deb.debian.org jessie Release.gpg [2,373 B]                          
Get:7 http://deb.debian.org jessie Release [148 kB]                                               
Get:8 http://apt.postgresql.org jessie-pgdg/9.6 amd64 Packages [20 B]        
Get:9 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:10 http://deb.debian.org jessie/main amd64 Packages [9,064 kB]
Fetched 10.0 MB in 5s (2,000 kB/s)     
Reading package lists... Done
postgresql-9.6-postgis-2.3:
  Installed: (none)
  Candidate: 2.3.1+dfsg-1.pgdg80+1
  Version table:
     2.3.1+dfsg-1.pgdg80+1 0
        500 http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg/main amd64 Packages
root@6e812f2b4c93:/# 

```

**Comment by ImreSamu** [comment]
Similar problem: https://github.com/appropriate/docker-postgis/issues/43

Maybe it is worth to add extra info to the `Dockerfile` ?   ( cc @md5  )
like this:
```Dockerfile
MAINTAINER Mike Dillon <mike@appropriate.io>

ENV POSTGIS_MAJOR 2.3
ENV POSTGIS_VERSION 2.3.0+dfsg-2.pgdg80+1

RUN apt-get update \
      && echo "=========================================================================" \
      && echo "List: Avaialable packages for postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR" \
      && echo "- if some problems - check and modify the ENV POSTGIS_VERSION" \
      && apt-cache policy postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
      && echo "=========================================================================" \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION \
           postgis=$POSTGIS_VERSION \
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/postgis.sh
```

**Comment by md5** [comment]
This is indeed the same issue as #43. I've opened PR #48 to fix this.
