### ISSUE TITLE
including HEALTHCHECK

### ISSUE THREAD

**Issue by Woile** [appropriate/docker-postgis#50]
Any plans on including docker new HEALTHCHECK?

https://docs.docker.com/engine/reference/builder/#/healthcheck

This is really useful because usually the db is not ready when other services are.

**Comment by md5** [comment]
See my thoughts on this issue in https://github.com/appropriate/docker-postgis/issues/34#issuecomment-233194764

**Comment by Woile** [comment]
Thanks @md5, yeah it makes totally sense to have the HEALTHCHECK into postgres main docker image. Thank you!
