### ISSUE TITLE
POSTGIS_VERSION upgrade

### ISSUE THREAD

**Issue by ryohang** [appropriate/docker-postgis#55]
I found the POSTGIS_VERSION is not longer available for building docker template.
It appears to be upgrading from 
ENV POSTGIS_VERSION 2.3.2+dfsg-1exp**1**.pgdg80+1 to ENV POSTGIS_VERSION 2.3.2+dfsg-1exp**2**.pgdg80+1

**Comment by md5** [comment]
I've opened #56 to fix this. If you'd like to make a PR yourself next time, you can can run `make update`.
