### ISSUE TITLE
Provide postgis_sfcgal extension

### ISSUE THREAD

**Issue by ianmcderp** [appropriate/docker-postgis#57]
Hey Mike,

that's a great image of PostGIS - I was wondering if you could add PostGIS' `postgis_sfcgal` extension to your `docker-postgis 9.6-2.3` image too? I'd provide you a pull request, ofc.

Kind regards,
Matthias R.

**Comment by md5** [comment]
It looks like this extension wouldn't require any additional Apt packages on the Debian-based image, but it isn't clear to me whether it's supported on Alpine. Can you address whether it could be included in the Alpine image and whether it would require any additional packages in that case?

As for a PR, I'd be happy for you to submit one, assuming we can support the extension on both Debian and Alpine. I'll want to PR to update the two template Dockerfiles and to update all the version-specific Dockerfiles (by running `make update`).

**Comment by md5** [comment]
I looked at this again yesterday and found that `sfcgal` is not packaged for Alpine. That would be a prerequisite of enabling it in this image.

It should be pretty easy to use the Debian-based image and install the extension yourself from and initdb.d script.

**Comment by md5** [comment]
Well, I suppose we could build `sfcgal` from source in this image...

**Comment by ianmcderp** [comment]
I don't have any numbers, but according to the information from the SCFCGAL website (http://www.sfcgal.org/), I assume that this library provides very interesting and curcial operations for 3D operations:

> SFCGAL is a C++ wrapper library around CGAL with the aim of supporting ISO 19107:2013 and OGC Simple Features Access 1.2 for 3D operations.

and

> Geometry coordinates have an exact rational number representation and can be either 2D or 3D. Among supported geometry types are :
> 
>     Points
>     LineStrings
>     Polygons
>     TriangulatedSurfaces
>     PolyhedralSurfaces
>     GeometryCollections
>     Solids
> 
> Supported operations include :
> 
>     WKT reading and writing with exact rational number representation for coordinates
>     Intersection operations and predicates
>     Convex hull computation
>     Tessellation
>     Extrusion
>     Area and distance computation
>     Minkovski sums
>     Contour offsets
>     Straight skeleton generations

From my point of view, they would enrich your image massively! 👍

**Comment by md5** [comment]
I will accept a PR for this, but I'm closing the issue.

**Comment by disarticulate** [comment]
it's not trivial  to get SFC. Here's the script i have in a older dockerfile:
```
ENV GEOS_VERSION=3.6.2
ENV GDAL_VERSION=2.3.1
ENV PROJ4_VERSION=5.1.0
ENV CGAL_VERSION=4.12
ENV SFCGAL_VERSION=1.3.6

#from http://trac.osgeo.org/geos/
ENV GEOS http://download.osgeo.org/geos/geos-$GEOS_VERSION.tar.bz2
#from http://trac.osgeo.org/gdal/wiki/DownloadSource
ENV GDAL http://download.osgeo.org/gdal/$GDAL_VERSION/gdal-$GDAL_VERSION.tar.gz
#from http://proj4.org/download.html
ENV PROJ http://download.osgeo.org/proj/proj-$PROJ4_VERSION.tar.gz
#from https://www.cgal.org/releases.html
ENV CGAL https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-$CGAL_VERSION/CGAL-$CGAL_VERSION.tar.xz
#from https://github.com/Oslandia/SFCGAL/releases
ENV SFCGAL https://github.com/Oslandia/SFCGAL/archive/v$SFCGAL_VERSION.tar.gz

#TODO make PROCESSOR_COUNT dynamic
#built by docker.io, so reducing to 1. increase to match build server processor count as needed
ENV PROCESSOR_COUNT 1

##Installation

#postgis required packages, PG_MAJOR from parent container
#lib building packages
#for address_standardizer

WORKDIR /install-postgis

WORKDIR /install-postgis/geos
ADD $GEOS /install-postgis/geos.tar.bz2
RUN tar xf /install-postgis/geos.tar.bz2 -C /install-postgis/geos --strip-components=1
RUN ./configure && make -j $PROCESSOR_COUNT && make install
RUN ldconfig
WORKDIR /install-postgis
RUN test -x geos

WORKDIR /install-postgis/gdal
ADD $GDAL /install-postgis/gdal.tar.gz
RUN tar xf /install-postgis/gdal.tar.gz -C /install-postgis/gdal --strip-components=1
RUN ./configure --with-geos=/usr/local/bin/geos-config && make -j $PROCESSOR_COUNT && make install
RUN ldconfig
WORKDIR /install-postgis
RUN test -x gdal

WORKDIR /install-postgis/proj
ADD $PROJ /install-postgis/proj.tar.gz
RUN tar xf /install-postgis/proj.tar.gz -C /install-postgis/proj --strip-components=1
RUN ./configure && make -j $PROCESSOR_COUNT && make install
WORKDIR /install-postgis
RUN test -f /usr/local/include/proj_api.h

WORKDIR /install-postgis/cgal
ADD $CGAL /install-postgis/cgal.tar.xz
RUN tar xf /install-postgis/cgal.tar.xz -C /install-postgis/cgal --strip-components=1
RUN cmake . && make -j $PROCESSOR_COUNT && make install
WORKDIR /install-postgis
#RUN test -d /usr/local/lib/CGAL

WORKDIR /install-postgis/sfcgal
ADD $SFCGAL /install-postgis/sfcgal.tar.gz
RUN tar xf /install-postgis/sfcgal.tar.gz -C /install-postgis/sfcgal --strip-components=1
RUN cmake . && make -j $PROCESSOR_COUNT && make install
WORKDIR /install-postgis
RUN test -x $sfcgal_config

WORKDIR /install-postgis/postgis
ADD $POSTGIS /install-postgis/postgis.tar.gz
RUN tar xf /install-postgis/postgis.tar.gz -C /install-postgis/postgis --strip-components=1
RUN ./configure --with-geosconfig=/usr/local/bin/geos-config \
	--with-gdalconfig=/usr/local/bin/gdal-config \
	--with-sfcgal=/usr/local/bin/sfcgal-config \
	--with-projdir=/usr/local \
	--with-raster \
	--with-topology \
	&& make
WORKDIR /install-postgis/postgis/extensions/postgis
RUN make -j $PROCESSOR_COUNT && make install
WORKDIR /install-postgis/postgis/extensions/postgis_topology
RUN make -j $PROCESSOR_COUNT && make install
WORKDIR /install-postgis/postgis
RUN make install
WORKDIR /install-postgis
RUN ldconfig
```
