### ISSUE TITLE
Viewing in QGIS?

### ISSUE THREAD

**Issue by iamlukesky** [appropriate/docker-postgis#61]
How would I go about viewing my PostGIS data in QGIS? Since the container does not expose any ports I'm not sure how I'm supposed to go about doing it.

**Comment by ImreSamu** [comment]
@iamlukesky :  
"This image is based on the [official postgres image](https://hub.docker.com/_/postgres/)"
so you can find all information in https://hub.docker.com/_/postgres/  , 

The official postgres image : standard port is 5432  -  see [docker-library/postgres:Dockerfile](https://github.com/docker-library/postgres/blob/bef8f02d1fe2bb4547280ba609f19abd20230180/9.6/Dockerfile#L133)

If you want to use via QGIS maybe you have to use port forwarding ~ `docker run -p 5432:5432   ...`

**Comment by iamlukesky** [comment]
For some reason or other this didn't work first time I tried it. Now it works fine ¯\_(ツ)_/¯
