### ISSUE TITLE
Postgres 10 releae?

### ISSUE THREAD

**Issue by vincent-dm** [appropriate/docker-postgis#62]
Hi,

I'm wondering if you are planning to release a version of this image based on the newly released PostgreSQL 10.

Thanks!

**Comment by tdamsma** [comment]
I am working on it here: https://github.com/appropriate/docker-postgis/pull/63

**Comment by vincent-dm** [comment]
@tdamsma great, thanks!

**Comment by vincent-dm** [comment]
Thanks @tdamsma and @md5
