### ISSUE TITLE
Keep Postgis version along with Postgres version in image tags

### ISSUE THREAD

**Issue by eshigee** [appropriate/docker-postgis#68]
I suggest adding additional tags that will allow selecting specific version of Postgis. Recent postgis upgrade is breaking production systems (requires manual postgis upgrade).

**Comment by md5** [comment]
This has been discussed many many times (just search the issues for "tag"). The unfortunate fact is that between Docker Hub and Docker Cloud, I don't have a good build system that allows me to easily manage tags for multiple versions. This is further complicated by the release management policy for the PostgreSQL repository at PGDG (particularly the fact that they remove old versions of packages and they only ever offer the `postgis` package from the latest release for download).

If someone could offer some concrete suggestions or PRs for what they'd like to see me do, I'm willing to discuss some more, but the fact is that I don't even use this image myself and I don't want to invest a ton of my time maintaining it.

In the meantime, you should be able to pull the image by SHA256 sum from Docker Hub to get a 2.3.2. or earlier version of the image. If you're building 2.3 images yourself, you'll need to adjust the `Dockerfile` to update to the latest 2.3 package that exists (2.3.3 I believe) and remove the `postgis` package from your image.

**Comment by md5** [comment]
#18 and #26 seem to be the most relevant issues, though this has been a recurring topic of discussion on other issues and PRs as well.
