### ISSUE TITLE
Alpine image is missing libprotobuf-c

### ISSUE THREAD

**Issue by stepankuzmin** [appropriate/docker-postgis#71]
Hi there! It seems that alpine image is missing `libprotobuf-c` (probably `protobuf-c-dev` package). So you can't use `ST_AsMVTGeom`.

**Comment by md5** [comment]
I'd welcome a PR. Otherwise, it will probably take me a while to get around to this.

**Comment by costefan** [comment]
What is the status of this issue?

**Comment by md5** [comment]
I'd still welcome a PR. This isn't something I have time to do myself

**Comment by stepankuzmin** [comment]
@md5 I've made a PR for this #80

**Comment by stepankuzmin** [comment]
Fixed in #80
