### ISSUE TITLE
dickerhub: Build path does not exist: ./9.3-2.3

### ISSUE THREAD

**Issue by winsento** [appropriate/docker-postgis#79]
All builds filed on https://hub.docker.com/r/mdillon/postgis/builds/

For example https://hub.docker.com/r/mdillon/postgis/builds/bjmbpsk2c9afknc9lsvsae6/

**Comment by md5** [comment]
The builds actually run on Docker Cloud now. I wasn't able to get the builds to trigger automatically anymore on Docker Hub, so I turned off that flag. I'm you sure if you can see this page, but the builds are here: https://cloud.docker.com/app/mdillon/repository/docker/mdillon/postgis/builds

The builds should still be pushed to the same registry, but there hasn't been a build in a while. I'll make sure it builds pushes after #82 is merged.

**Comment by md5** [comment]
The latest builds on Docker Cloud updated the tags: https://hub.docker.com/r/mdillon/postgis/tags/
