### ISSUE TITLE
Creating tags for minor version of Postgres

### ISSUE THREAD

**Issue by NicoTexas** [appropriate/docker-postgis#86]
Hi,

I see you are creating your images from postgres:9.5 for example.

The issue with that is you will get the 9.5 version at the image build time (could be 9.5.2 or whatever).
As a result you will not getting the latest 9.5 when pulling your image. Which is a bit misleading.

So, to ensure the latest version part of your image, you would need to build

```
FROM postgres:9.5.10
```
and tag it appropriately mdillon/postgis:9.5.10

Which bring the question of the versioning of PostGIS in the tag too.

mdillon/postgis:9.5.10-2.4.3

What do you think?

**Comment by md5** [comment]
Please see #8, #18, #26, #68, and #72.

As for whether or not you'll have an old version of `postgres`, there was a repository link in place when the builds were happening on Docker Hub, but I'm not sure that's still the case with the Docker Cloud build... I don't know if there's a good way to replicate that without running my own process somewhere to watch Docker Hub for updates of the `postgres` image and trigger a build on Docker Cloud.
