### ISSUE TITLE
february 8th Postgresql update

### ISSUE THREAD

**Issue by pascalheraud** [appropriate/docker-postgis#87]
Could you please update docker to last postgresql versions ?
I tested and got an error for 9.5-2.4 but 10.2 works well.

10.2, 9.6.7, 9.5.11, 9.4.16, and 9.3.21.

**Comment by pascalheraud** [comment]
Hello, I can help if you need.

**Comment by znmeb** [comment]
P.S.: There is now a March 1 update - 10.3 etc. - somebody found a vulnerability in schema handling https://wiki.postgresql.org/wiki/A_Guide_to_CVE-2018-1058:_Protect_Your_Search_Path

**Comment by md5** [comment]
I just manually triggered all the builds.

**Comment by pascalheraud** [comment]
thank you
