### ISSUE TITLE
Loading Tiger data

### ISSUE THREAD

**Issue by jgn** [appropriate/docker-postgis#90]
I'm just wondering if there is any pre-built scripting that loads into this Docker the Tiger data -- The steps here https://postgis.net/docs/postgis_installation.html#install_tiger_geocoder_extension at item 4 and after . . . Or even a Docker image that is already loaded. (I realize it would be voluminous.)

**Comment by md5** [comment]
This isn't a support forum for general PostGIS questions, even in the context of initializing a Docker container. Sorry.
