### ISSUE TITLE
Allow disabling unneeded extensions

### ISSUE THREAD

**Issue by vladimiroff** [appropriate/docker-postgis#92]
This images creates the following extensions: `postgis`, `postgis_topology`, `fuzzystrmatch` and `postgis_tiger_geocoder` on startup.

It makes bootstrapping the image way slower (not to mention that it does it at least twice). Would be great if it's possible to disable (e.g. with env variables) some of them.

**Comment by md5** [comment]
Please provide a PR if you're interested in this functionality. I don't see a huge problem with the list of extensions initialized by `initdb-postgis.sh` comes from an environment variable.

I'm going to close this issue in lieu of a PR.
