### ISSUE TITLE
ERROR: could not access file "$libdir/postgis-2.4": No such file or directory"  By using Postgresql 10 with Linux mint 18.1

### ISSUE THREAD

**Issue by bvl2016** [appropriate/docker-postgis#93]
Hello,
Anyone can help me how to fix my error in the object?
I can't neither to add nor to create the postgis extension.
Thank you.

**Comment by leonardofmed** [comment]
Did you fix it?

**Comment by leonardofmed** [comment]
I fixed the issue by reinstalling an older version of PostgreSQL(9.5) and PostGIS(2.3)

**Comment by chapmanjacobd** [comment]
I think `postgis-upgrade` should be a dependency of `postgis` but it is not :scream: 

I also have encountered this issue several times and I just discovered that by installing `postgis-upgrade` then running `sudo postgresql-setup --upgrade` will actually work

**Comment by asolako** [comment]
> I think `postgis-upgrade` should be a dependency of `postgis` but it is not scream
> 
> I also have encountered this issue several times and I just discovered that by installing `postgis-upgrade` then running `sudo postgresql-setup --upgrade` will actually work

Thank you! I can confirm that this solved my issue when I upgraded from Fedora 28 to Fedora 30 (via 29).
