### ISSUE TITLE
How do we know when database is ready?

### ISSUE THREAD

**Issue by martinthurn** [appropriate/docker-postgis#95]
For regular (non-PostGIS) postgres containers, we can wait for the message "database system is ready to accept connections" to appear in the log.  However, your mdillon/postgres never seems to print that message.  How can external apps such as docker-maven-plugin know when the database is ready?

**Comment by ImreSamu** [comment]
Maybe this is useful : 

[github.com/docker-library/postgres#146:"How to determine when new container is truly "ready"](https://github.com/docker-library/postgres/issues/146)

//  This image is based on the official [postgres image](https://github.com/docker-library/postgres) ; so most of the postgres - best practice can be reused here.

**Comment by martinthurn** [comment]
Right you are (of course).  My apologies and sorry to bother you.  I found and fixed another problem that was interfering with the log message detection.
